---
driver:
  name: dokken
  chef_version: latest
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      image: centos:7
      platform: rhel
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install lsof which systemd-sysv initscripts wget net-tools 
      # privileged: true
      # volumes:
      #   - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd

suites:
  - name: default
    data_bags_path: "test/fixtures/data_bags" 
    run_list:
      - recipe[base_server::default]
    # verifier:
    #   inspec_tests:
    #     - test/integration/default
    attributes: {
      "authorization": {
        "sudo": {
          "users": ["kitchen"],
          "passwordless": true
        }
      }
    }

