---
driver:
  name: docker
  use_sudo: false
  memory: 1512m
  private_key: "<%= ENV['HOME'] %>/.ssh/testkitchen_docker_id_rsa"
  public_key: "<%= ENV['HOME'] %>/.ssh/testkitchen_docker_id_rsa.pub"

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: 12.21.3

verifier:
  name: inspec

platforms:
  # - name: ubuntu-16.04
  #   driver_config:
  #     image: ubuntu:16.04
  #     platform: ubuntu
  - name: centos-7.3
    driver_config:
      image: centos:7.3.1611
      platform: rhel
      run_command: /usr/lib/systemd/systemd
      privileged: true
      provision_command:
        - yum -y install lsof which systemd-sysv initscripts wget net-tools 
      #   - yum -y --enablerepo=extras install epel-release

suites:
  - name: default
    data_bags_path: "test/fixtures/data_bags" 
    run_list:
      - recipe[base_server::default]
    # verifier:
    #   inspec_tests:
    #     - test/integration/default
    attributes: {
      "authorization": {
        "sudo": {
          "users": ["kitchen"],
          "passwordless": true
        }
      }
    }

